[tools]
usage = "latest"
python = "3.12"
neovim = "latest"
uv = "latest"
node = "22"
age-plugin-yubikey = "latest"
awscli = "latest"
age = "latest"
pre-commit = "latest"
fzf = "latest"
ruff = "latest"
eza = "latest"
zellij = "latest"
dust = "latest"
zoxide = "latest"
cookiecutter = "latest"
btop = "latest"
bitwarden = "latest"
bat = "latest"
ripgrep = "latest"
